name: Backup Firestore

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

env:
  PROJECT_ID: fairly-settled-e2466
  BUCKET: gs://backup-restoration-02 # Updated bucket name

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Set gcloud project
        run: gcloud config set project $PROJECT_ID

      - name: Firestore export
        run: gcloud firestore export --database=fairlysettled $BUCKET
